// Generated by https://quicktype.io

export interface TransactionPaymentResponse {
    data: Data;
    meta: Meta;
}

export interface Data {
    id:                  string;
    created_at:          string;
    finalized_at:        null;
    amount_in_cents:     number;
    reference:           string;
    customer_email:      string;
    currency:            string;
    payment_method_type: string;
    payment_method:      PaymentMethod;
    status:              string;
    status_message:      null;
    billing_data:        null;
    shipping_address:    null;
    redirect_url:        null;
    payment_source_id:   number;
    payment_link_id:     null;
    customer_data:       null;
    bill_id:             null;
    taxes:               any[];
}

export interface PaymentMethod {
    type:         string;
    extra:        null[];
    installments: number;
}

export interface Meta {
}
